### ISSUE TITLE
Support globs for assets?

### ISSUE THREAD

**Issue by fnlctrl** [jharris4/html-webpack-include-assets-plugin#11]
Something like
```js
new HtmlWebpackIncludeAssetsPlugin({
    assets: ['foo/*.css']
})
```

**Comment by mmiller42** [comment]
This was asked before: see https://github.com/jharris4/html-webpack-include-assets-plugin/issues/5

**Comment by jharris4** [comment]
As @mmiller42 said, this question has already been answered

**Comment by jharris4** [comment]
FYI, version `0.0.8` added support for `asset.glob`, see updated example in the README.
