### ISSUE TITLE
Minor version

### ISSUE THREAD

**Issue by mmiller42** [jharris4/html-webpack-include-assets-plugin#13]
Super trivial thing, but might be more semver to release a `0.1.0` instead of `0.0.x`. I'd imagine that this project is used enough and is popular enough to have a somewhat stable API. When npm-installing a package at 0.0, however, npm always resolves to the exact version, without using `~` or `^`. I'm not sure, but I don't think 0.0.x is technically valid according to the semver spec.

**Comment by jharris4** [comment]
I think it is a valid semver, and I've typically been using `>=0.0.x` in my package.json... But yeah, I suppose I could bump the version to `1.0.0` or something for the next version.

**Comment by mmiller42** [comment]
Probably emphasis is that new features are being introduced in this project, while only the patch version is incremented. Technically, new (but backwards-compatible) features should increment minor, while only bugfixes should increment patch.

**Comment by jharris4** [comment]
yeah, you have a good point that it should be minor version bumps since backwards compatibility has been maintained. I'll switch over to `1.0.0` for the next release.

**Comment by jharris4** [comment]
version `1.0.0` was just released. Thanks for the feedback.
