### ISSUE TITLE
Support for hot reloading

### ISSUE THREAD

**Issue by chinchang** [jharris4/html-webpack-include-assets-plugin#17]
Can this plugin support hot reloading? For example, for a CSS asset, it could dynamically replace the link tags.

**Comment by jharris4** [comment]
The primary purpose of this plugin is to support including (static) assets that are not part of your regular source code.

If you want to use hot reloading, you should just place the assets inside your regular source directories, and let webpack handle the inclusion (and hot reloading if desired).

I'm closing this issue, but feel free to leave additional comments if you need more clarification
