### ISSUE TITLE
keep hash unchanged

### ISSUE THREAD

**Issue by saysmy** [jharris4/html-webpack-include-assets-plugin#18]
> hash: boolean

Specifying whether the assets should be appended with webpack's compilation hash. This is useful for cache busting. Default is false.

hi, Are there any ways to keep the hash value unchanged and only generate the hash based on the content?

**Comment by jharris4** [comment]
The hash is being generated by `webpack`.

If you want to change the `hash` that is generated, you'll need to change your webpack config accordingly.

I'm closing this issue, but happy to help if you have further questions that are specific to this plugin.
