### ISSUE TITLE
Wildcard not matched, instead simply outputted in template

### ISSUE THREAD

**Issue by kroko** [jharris4/html-webpack-include-assets-plugin#19]
Hi,

I have a setup very similar to [first example in the docs](https://github.com/jharris4/html-webpack-include-assets-plugin#example)

* File called`preflight.js` exists and that is not (and should be not) added in webpack entry.
* It is copied to webpack configs output path using `copy-webpack-plugin`. On the way it receives hashing for filename itself which will change only when contents change.
* I am using `html-webpack-plugin` to generate template, i this example auto injecting default one.
* Accordingly to docs I specify minimatch ready string `preflight.*.js` which would match stuff in webpack's output path (in my case `path: path.join(__dirname, 'public/assets')`)

I tried both

 * `**/*preflight.*.js`
 * `preflight.*.js`

My test config is

```javascript

// this copies file from 'src/preflight.js to public/assets/preflight.hash.js
config.plugins.push(new CopyWebpackPlugin([
  {
    from: 'src/preflight.js',
    to: `[name].[hash].[ext]`
  }
]));

config.plugins.push(new HtmlWebpackPlugin({
  title: `TEST`,
  filename: `${path.join(__dirname, 'public')}/index.html`,
  inject: true,
  hash: false,
  cache: true,
  showErrors: true,
  chunksSortMode: 'auto',
  excludeChunks: [],
  xhtml: false,
  alwaysWriteToDisk: true,
  minify: false
}));

config.plugins.push(new HtmlWebpackHarddiskPlugin());

config.plugins.push(new HtmlWebpackIncludeAssetsPlugin({
  assets: [
    'preflight.*.js'
  ],
  append: false,
  hash: false
}));
```

Template output (prod build, not devserver) is 

```html

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>TEST</title>
  <link href="//webpacktest-codesplitting.test/assets/site.3c550d0e6ef1b0cc4345.css" rel="stylesheet"></head>
  <body>
<script type="text/javascript" src="//webpacktest-codesplitting.test/assets/preflight.*.js"></script><script type="text/javascript" src="//webpacktest-codesplitting.test/assets/manifest.27fead361ac3388ca95d.js"></script>
<script type="text/javascript" src="//webpacktest-codesplitting.test/assets/vendor.d52f339f6cf1da9e710d.js"></script>
<script type="text/javascript" src="//webpacktest-codesplitting.test/assets/site.3c550d0e6ef1b0cc4345.js"></script>
</body>
</html>
```
Whatever I put into `assets` key is outputted _as is_ within template. As you can see from sourcefile name I am testing code splitting 😄 . Disabling that does not change anything.

What am I missing? Did I overlook the docs and there is no actual minimatching against real files in filesystem that are copied over to output path?

Thanks!

| software         | version(s)
| ---------------- | -------
| node             | 8.9.4
| npm              |  5.6.0
| Operating System |  macOS 10.13.2
| Webpack |  3.10.0
| copy-webpack-plugin |  4.3.1
| html-webpack-plugin |  2.30.1
| html-webpack-harddisk-plugin |  0.1.0
| html-webpack-include-assets-plugin |  1.0.2

**Comment by jharris4** [comment]
The last time I looked into this, the issue was because the `copy-webpack-plugin` was not copying the assets until *AFTER* the `html-webpack-plugin` (and therefore this plugin) had completed processing.

This makes it impossible to do anything other than look at the *source* files to do minimatching.

At the time I last looked into this, development on the `copy-webpack-plugin` had mostly stopped but it has since been taken over by the webpack team so maybe they'll be able to make the changes to better support the HtmlWebpackPlugin. There is not much that can be done without that... :-(

Here are some issues that are related:
https://github.com/webpack-contrib/copy-webpack-plugin/issues/133
https://github.com/webpack-contrib/copy-webpack-plugin/issues/15

**Comment by kroko** [comment]
Understood.  
I'll give [Webpack File Manager Plugin](https://github.com/gregnb/filemanager-webpack-plugin) a try and report back how it goes.

**Comment by kroko** [comment]
Well, combination with `filemanager-webpack-plugin` does not work too.

If I change `CopyWebpackPlugin` in the original post to 

```javascript
// ----------------
// FileManagerPlugin

config.plugins.push(new FileManagerPlugin({
  onStart: {
    copy: [
      {
        source: 'src/preflight.js',
        destination: 'public/assets/preflight.123.js'
      }
    ],
    move: [],
    delete: [],
    mkdir: []
  },
  onEnd: {}
}));
```
I can observe that file emitting really differs, `preflight.123.js` is the first thing to arrive in output path.

However compiled HTML still contains not resolved minimatch against preflight.123.js (contains raw string as specified in HtmlWebpackIncludeAssetsPlugin `assets` key).

```html
<script type="text/javascript" src="//webpacktest-codesplitting.test/assets/preflight.*.js">
```

**Comment by kroko** [comment]
If I strip this aspect of before/after

> the issue was because the copy-webpack-plugin was not copying the assets until AFTER the html-webpack-plugin (and therefore this plugin) had completed processing.

by 
- dropping file copying in webpack config entirely (both CopyWebpackPlugin  and FileManagerPlugin)
- manually place 'public/assets/preflight.123.js', so that the file physically really is there from the beginning of the as far as code is concerned
- disable output path cleanup before building (cleaning `public/assets/ directory`)
- building the solution

HtmlWebpackIncludeAssetsPlugin still does not find `preflight.123.js` by specifying `assets: ['preflight.*.js']` although examples in your documentation imply that assets string will be matched against everything that is in webpack's output path if _relative path_ is used.

**Comment by jharris4** [comment]
Sorry, it's a bit hard for me to follow your examples. Do you think you could create a reproduction of the problem so I can take a quick look?

**Comment by kroko** [comment]
Hi,

I revisited this issue - my bad.  
I had the assumption that if strings are supplied to `assets`, then matching will also be done. However it is done only when objects are passed to `assets`.

Thus to make it work I use *FileManagerPlugin* to copy files to webpack's output path. It does it `onStart`. In my example `src/preflight/preflight.{js|css}` is copied to `public/assets/preflight.123.{js|css}` (`public/assets/` is webpack's output path).

And instead of trying to match those files in output path using

```javascript
config.plugins.push(new HtmlWebpackIncludeAssetsPlugin({
  assets: [
    'preflight.*.js',
    'preflight.*.css'
  ]
}));
```

the way I did in original post https://github.com/jharris4/html-webpack-include-assets-plugin/issues/19#issue-291075864 and later comment https://github.com/jharris4/html-webpack-include-assets-plugin/issues/19#issuecomment-360158998
I have to do

```javascript
config.plugins.push(new HtmlWebpackIncludeAssetsPlugin({
  assets: [
    {
      path: '',
      glob: 'preflight.*.js',
      globPath: outputPath
    },
    {
      path: '',
      glob: 'preflight.*.css',
      globPath: outputPath
    }
  ]
}));
```
`outputPath` is webpack's output directory.

It _works_.

---

And FYI. I can use it only for case where

* Have files **copied** (not built / included in webpack runtime) to output directory
* Have them **referenced** in built HTML using *HtmlWebpackPlugin*

The other need 

* Have files **copied** (not built / included in webpack runtime) to output directory
* Have them **inlined** in built HTML using *HtmlWebpackPlugin*

will not work. `script-ext-html-webpack-plugin` by having

```javascript
config.plugins.push(new ScriptExtHtmlWebpackPlugin({
  inline: [
    /preflight.*.js$/
  ]
}));
```
it will throw `ERROR in   Error: ScriptExtHtmlWebpackPlugin: no asset with href 'preflight.123.js'`

Which is funny because it _knows_ that the file is called `'preflight.123.js'` so something is matched. 

`script-ext-html-webpack-plugin` is the plugin I use for inlining manifest/runtime in HTML when splitting code using `CommonsChunkPlugin` and it works.

Some bug or what https://github.com/numical/script-ext-html-webpack-plugin/issues/13

Yes, I've tried switching plugin order.

My current sollution if I want to 

* Have files **copied** (not built / included in webpack runtime) to output directory
* Have them **inlined** in built HTML using *HtmlWebpackPlugin*

is to have custom keys in `HtmlWebpackPlugin` that have values of contents I want to inline

```javascript
config.plugins.push(new HtmlWebpackPlugin({
  fsInlineContents: {
    'preflight.js': fs.readFileSync(path.join(__dirname, 'src/preflight/preflight.js'), 'utf8'),
    'preflight.css': fs.readFileSync(path.join(__dirname, 'src/preflight/preflight.css'), 'utf8')
  }
}));
```
and then in template I echo the contents out by doing

```ejs
<script><%= htmlWebpackPlugin.options.fsInlineContents['preflight.js'] %></script>
<style><%= htmlWebpackPlugin.options.fsInlineContents['preflight.css'] %></style>
```

**Comment by jharris4** [comment]
Yeah, it gets tricky when you're dealing with assets that are being copied to the webpack output path. You need to make sure those assets are copied before htmlWebpackPlugin starts processing things or else you start to get unexpected results...

Thanks for documenting your findings, and for the suggestions of using `htmlWebpackPlugin.options.fsInlineContents` or `ScriptExtHtmlWebpackPlugin`.

I'll take a look at those the next time I have assets that I want to copy and include.

**Comment by kroko** [comment]
note that `fsInlineContents` is my made up key name, it can be anything that does not clash with built in keys.
