### ISSUE TITLE
Plugin doesn't work with inject:false in HtmlWebpackPlugin

### ISSUE THREAD

**Issue by Mehdi-Hp** [jharris4/html-webpack-include-assets-plugin#20]
I have this cause multiple assets injection
```javascript
new HtmlWebpackPlugin({
  template: 'views/index.html',
  inject: true,
  filename: 'index.html'
}),
new HtmlWebpackIncludeAssetsPlugin({
  assets: [
    'main.bundle.css',
    'bundle.js'
  ],
    append: true,
    publicPath: 'production/'
})
```
And the result is multiple injection:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
  <link href="/main.bundle.css" rel="stylesheet"><link href="production/main.bundle.css" rel="stylesheet"></head>
  <body>
    <div id="app"></div>
    <script type="text/javascript" src="/bundle.js"></script><script type="text/javascript" src="production/bundle.js"></script></body>
</html>
```
I know `<link href="/main.bundle.css" rel="stylesheet">` is caused by `HtmlWebpackPlugin` itself, But if I set `inject` as `false`, then `HtmlWebpackIncludeAssetsPlugin` doesn't work at all!

**Comment by jharris4** [comment]
By setting `HtmlWebpackPlugin`'s `inject` to false, aren't you telling it to not do anything?

It seems logical to me that `HtmlWebpackIncludeAssetsPlugin` will not do anything if you tell `HtmlWebpackPlugin` not to do anything.

Please clarify if I'm not understanding your issue properly...

**Comment by Mehdi-Hp** [comment]
That's true. I want `HtmlWebpackPlugin` stop injecting things and `HtmlWebpackIncludeAssetsPlugin` handle the works.   
After all, I don't care what config should be. I just don't want to have duplicate assets injected to HTML file.

**Comment by jharris4** [comment]
To be clear `HtmlWebpackIncludeAssetsPlugin` is a plugin FOR `HtmlWebpackPlugin` and cannot work independently from it.

This plugin just tells `HtmlWebpackPlugin` which extra assets to inject, so I'm sorry but what you're asking for is not possible.

**Comment by BeauAgst** [comment]
@jharris4 is there no way for us to not inject the chunks, but still inject the static assets? I have the same use-case
