### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by aulisius** [jharris4/html-webpack-include-assets-plugin#22]
Hey, I can see in the commit logs that the plugin is now compatible with webpack@4. Can you also update npm with this version?

Thanks,
Faizaan.

**Comment by jharris4** [comment]
Hi, version `1.0.3` with webpack@4 compatibility was published to npm 3 days ago, I had just forgotten to push the changes to GitHub. lol

I've pushed the changes now. Good luck with the webpack 4 migration!
