### ISSUE TITLE
Ignoring publicPath when path is started with 'http(s)://' or '//'

### ISSUE THREAD

**Issue by ElvisKang** [jharris4/html-webpack-include-assets-plugin#27]
Hi!
My project uses some third-party libraries  downloaded from CDN and some local static files with public path '/xyz' in publication env.

I think include-assets-plugin need to ignore configuration of publicPath when the path string is started with 'http(s)://' or '//' , and I needn't to create HtmlWebpackIncludeAssetsPlugin object twice.

**Comment by jharris4** [comment]
Hi there. I'm a little confused about how paths starting with `http://` etc are an issue for you with this plugin. This plugin will scan files/directories you specify for assets to include and does not normally have to deal with urls in filenames..

How are real links getting mixed in here along with regular files?

Are you saying that your **filenames** are actually named `https://domain.com/my/file.css` ???

If so, then you can use the `glob` example from the README to do something like this:

```
new HtmlWebpackIncludeAssetsPlugin({
  assets: [{ path: 'css', glob: '(!https*)*.css', globPath: 'full/path/to/src/directory/with/files' }],
  append: true
})
```

I'd have to google to the glob syntax to get exactly what you need, but the above should work if you get the glob right.

If this is not what you need, then please provide a little more background information.

**Comment by ElvisKang** [comment]
My configuration is like ：
```javascript
  new HtmlWebpackIncludeAssetsPlugin({
    assets: [
      'css/bootstrap.min.css',
      'css/bootstrap-theme.min.css',
      { path: 'https://fonts.googleapis.com/css?family=Material+Icons', type: 'css' }
    ],
    append: false,
    publicPath: '/xyz/'
  })
```
This will output a html with：
```html
  <link href=/xyz/css/bootstrap.min.css rel=stylesheet>
  <link href=/xyz/css/bootstrap-theme.min.css rel=stylesheet>
  <link href="/xyz/https://fonts.googleapis.com/css?family=Material+Icons" rel=stylesheet>
```

**Comment by jharris4** [comment]
So it looks like you're just trying to use the plugin configuration to output strings into your html template without actually including any assets?

That might be an interesting idea, but I'm not sure that this plugin is the right place for that kind of functionality.

This name of this plugin has `include-assets` in the name, and what you're describing is not really that. It's more like template injection.

If you feel like trying it out and making a PR I'd be happy to review.

**Comment by ElvisKang** [comment]
Thanks for your reply.

I use the example in REAME.md for explaining my problem.

In my project , some static files are copied to assets folder ( /assets/** ) by 
 CopyWebpackPlugin , which is the same as 'bootstrap.min.css' . Others are downloaded from CDN . 

So the configuration file is like : 

```javascript 
  new CopyWebpackPlugin([
    { from: 'node_modules/bootstrap/dist/css', to: 'css/'},
    { from: 'node_modules/bootstrap/dist/fonts', to: 'fonts/'}
  ]),
  new HtmlWebpackIncludeAssetsPlugin({
    assets: [
      'css/bootstrap.min.css',
      'css/bootstrap-theme.min.css',
      { path: 'https://fonts.googleapis.com/css?family=Material+Icons', type: 'css' }
    ],
    append: false,
    publicPath: '/xyz/'
  })
```
The output structure is 
```
├── assets
│   ├── css
│   │   ├── commons.css
│   │   ├──  // others 
│   ├── js
│   └── images
├── views
│   ├── pageA.html
│   └──  // others
```
In development env , the public path is '/'  ( `localhost:8080/assets/css/***` ) . And it need to be '/xyz' in production (`'www.example.com/xyz/views/pageA.html` and  `www.example.com/xyz/assets/css/***` ) . So when my html includes assets both from CopyWebpackPlugin and CDN ( HTTP URL ) . The config of public path will make the http urls to be `/xyz/https://fonts.googleapis.com/css?family=Material+Icons`

**Comment by jharris4** [comment]
Ok, your examples and the PR helped me to understand the problem now.

The `publicPath` option of assets is what you need (your PR was not actually necessary).

```new HtmlWebpackIncludeAssetsPlugin({ assets: 'http://www.foo.com/foobar.js', append: false, publicPath: false })```

will give you:

```<script type="text/javascript" src="http://www.foo.com/foobar.js"></script>```

Give that a try and let me know how it goes :-)

**Comment by jharris4** [comment]
Closing as the `publicPath` supports what you want like this:

```
plugins: [
          new HtmlWebpackPlugin(),
          new HtmlWebpackIncludeAssetsPlugin(
            { assets: 'local-with-public-path.js', append: false, publicPath: true }
          ),
          new HtmlWebpackIncludeAssetsPlugin(
            { assets: ['local-without-public-path.js', 'http://www.foo.com/foobar.js'], append: false, publicPath: false }
          )
        ]
```

**Comment by ElvisKang** [comment]
Ok, thank you for your help

**Comment by ElvisKang** [comment]
Sorry, I think we should reopen this issue.

For the configuration:
```javascript
  new CopyWebpackPlugin([
    { from: 'static/js', to: 'assets/js/'},
    { from: 'node_modules/bootstrap/dist/css', to: 'assets/css/'},
    { from: 'node_modules/bootstrap/dist/fonts', to: 'assets/fonts/'}
  ]),
  new HtmlWebpackIncludeAssetsPlugin({
    assets: [
      'assets/css/bootstrap.min.css',
      'assets/css/bootstrap-theme.min.css',
      'assets/js/jquery.min.js',
      { path: 'http://path/to/library/must/included/after/jquery', type: 'js' },
      'assets/js/other-static.js'
    ],
    append: false
  })
```

If the CDN's file (called `X`) depends on `jquery` and `other-static.js` depends on `X`,which means:
```
 Correct download order :  jQuery -> X -> other-static.js
```

The configuration will be verbose.

I think maybe you can add an attribute named 'publicPath' to single assets config object , which is like :
```javascript
{
   assets:[
     ...
     { path: 'http://path/to/library/must/included/after/jquery', type: 'js',publicPath:false }
     ....
     ],
    publicPath:'xyz'
}
```
