### ISSUE TITLE
Using order cause problems

### ISSUE THREAD

**Issue by yeatszhang** [jharris4/html-webpack-include-assets-plugin#31]
webpack v4
html-webpack-include-assets-plugin v1.0.4

When I using in this order

```javascript
plugins: [
  new CopyWebpackPlugin([
    { from: 'node_modules/bootstrap/dist/css', to: 'css/'},
    { from: 'node_modules/bootstrap/dist/fonts', to: 'fonts/'}
  ]),
  new HtmlWebpackPlugin({
    filename: 'a/index.html'
  }),
  new HtmlWebpackIncludeAssetsPlugin({
    files: ['a/**/*.html'],
    assets: ['css/a.css'],
    append: true
  }),
  new HtmlWebpackPlugin({
    filename: 'b/index.html'
  }),
  new HtmlWebpackIncludeAssetsPlugin({
    files: ['b/**/*.html'],
    assets: ['css/b.css'],
    append: true
  })
]
```

The first plugin 

```javascript
 new HtmlWebpackIncludeAssetsPlugin({
    files: ['a/**/*.html'],
    assets: ['css/a.css'],
    append: true
  }),
```
will not work.

I found that `HtmlWebpackIncludeAssetsPlugin` need using behind `HtmlWebpackPlugin`

I spend a lot of time to find the problem. I wish it to be fix or doc it.

**Comment by jharris4** [comment]
Hi, I've never tried having two HtmlWebpackPlugin instances like you show in your config. Is that the recommended way to do it?

Either way, if you can provide a reproducible test case I can try to look into what's happening.

**Comment by yeatszhang** [comment]
I found the problem when I wrote like this -  to generate html for each page in my CLI tools



```javascript
[{
  name: 'pageA',
  assets: [ 'asset1', 'asset2' ]
}, {
  name: 'pageB',
  assets: [ 'asset3', 'asset4' ]
}, {
  name: 'pageC',
  assets: [ 'asset5', 'asset6' ]
}].forEach(({ name, assets }) => {
  config.plugins.push(new HtmlWebpackPlugin({ filename: name + '.html' }))
  
  config.plugins.push(new HtmlWebpackIncludeAssetsPlugin({
      assets,
      files: name + '.html'
    }))
})
```

And I found only the last `HtmlIncludeAssets` works, I have to use two `forEach` to fix the problem

```javascript
const pageConfigs = [{
  name: 'pageA',
  assets: [ 'asset1', 'asset2' ]
}, {
  name: 'pageB',
  assets: [ 'asset3', 'asset4' ]
}, {
  name: 'pageC',
  assets: [ 'asset5', 'asset6' ]
}]

pageConfigs.forEach(({ name }) => {
   config.plugins.push(new HtmlWebpackPlugin({ filename: name + '.html' }))
})

pageConfigs.forEach(({ name, assets }) => {
 config.plugins.push(new HtmlWebpackIncludeAssetsPlugin({
      assets,
      files: name + '.html'
    }))
})
```



Cause no doc tell me the plugin relate to its order,  I spend a long time to locate the problem. T_T

**Comment by jharris4** [comment]
I wouldn't have thought using one vs two loops would make a difference, are you sure that's the problem?!

Either way, it looks like none of the tests for this plugin tries to use 2 instances of HtmlWebpackPlugin, so I should probably at least add a test for that! :-)

**Comment by yeatszhang** [comment]
I tested it several times and confirmed that there would be problems if HtmlWebpackPlugin HtmlWebpackIncludeAssetsPlugin was used interchangeably. :blush:

**Comment by jharris4** [comment]
oh I see, it's because you changed from mixing them in the plugin list to keeping them separate.

I guess that makes sense. But I think this is an issue with `HtmlWebpackPlugin`, so maybe it would be good to file an issue there?

**Comment by yeatszhang** [comment]
I think it is OK, please close it after the problem is solved. It is best to mark it in the document.

**Comment by jharris4** [comment]
Thanks for the feedback! I updated the README with the following text:

```
Note that some users have encountered issues with plugin ordering.

It is advisable to always place any HtmlWebpackPlugin plugins before any HtmlWebpackIncludeAssetsPlugin plugins in your webpack config.
```
