### ISSUE TITLE
A bug when using protocol-relative paths in assets 

### ISSUE THREAD

**Issue by huruji** [jharris4/html-webpack-include-assets-plugin#41]
I want to inject a script which via HTTPS when needed:

```js
{
	plugins: [
		new HtmlWebpackPlugin({
			template
		}),
		new HtmlWebpackIncludeAssetsPlugin({
			assets: [
				{
					path: '//polyfill.alicdn.com/polyfill.min.js',
					type: 'js',
					attributes: {
						crossorigin: 'anonymous'
					}
				}
			],
			resolvePaths: false,
			append: false
		})
	]
}
```

But the `.html` output added a `/`,  the link was `///polyfill.alicdn.com/polyfill.min.js`, It was wrong.

![image](https://user-images.githubusercontent.com/15937065/53892394-2babcf80-4067-11e9-8d24-e69edc669543.png)

**Env**
```json
html-webpack-include-assets-plugin    v1.0.7

html-webpack-plugin        v3.2.0

webpack     v4.28.2
```

**Comment by jharris4** [comment]
Oh interesting, I did not even know protocol relative urls existed! (https://www.paulirish.com/2010/the-protocol-relative-url/)

I'll have a look and see if there's an easy fix. Of course, a PR would be welcome if you'd like to have a look yourself... ;-)

**Comment by huruji** [comment]
well, I will have a look tommorrow when  I am free.

**Comment by jharris4** [comment]
Actually, there's a very easy fix for this. The `/` prefix is being added to your url because this is your `publicPath` from webpack.

If you add `publicPath: false` to your asset it should work, like this:

```
{
  path: '//polyfill.alicdn.com/polyfill.min.js',
  publicPath: false,
  type: 'js',
  attributes: {
    crossorigin: 'anonymous'
  }
}
```

**Comment by jharris4** [comment]
Can you give that a try and let me know if that fixes it?

**Comment by huruji** [comment]
oh, it works @jharris4

**Comment by jharris4** [comment]
Great, glad it was an easy fix!
