### ISSUE TITLE
could assets option support regexp match ?

### ISSUE THREAD

**Issue by superpig** [jharris4/html-webpack-include-assets-plugin#5]
because some cdn don't support query hash, i want to use the chunkhash of webpack. so i need to include my file like this:

```js
 new HtmlWebpackIncludeAssetsPlugin({
        assets: ['js/build/commonVendor.dll.*.js'],
        append: false     
});
```

**Comment by jharris4** [comment]
regexp or globs are not currently supported for assets, but it's pretty easy to write some code to do that yourself.

If you want to use globs (easier than regexp), then you can do something like this:

```
var glob = require("glob");
var path = require("path");

var directoryToSearch = path.resolve("js/build");
console.log("searching directory: ", directoryToSearch);

// default cwd is process.cwd() if you don't pass in globOptions
var globOptions = { cwd: directoryToSearch };

// assets will be an array of strings with all matching asset file names
var assets = glob.sync("commonVendor.dll.*.js", globOptions);
console.log("found files: ", assets);
```

**Comment by superpig** [comment]
thinks, it works well

**Comment by mikegleasonjr** [comment]
Just curious, what's preventing adding it to the core?

**Comment by jharris4** [comment]
@mikegleasonjr I haven't had a need for it personally, and adding it to the core just basically requires time to code it, and add unit tests etc.

I'm happy to review a PR if you're so inclined ;-)

**Comment by jharris4** [comment]
FYI, version `0.0.8` added support for `asset.glob`, see updated example in the README.
