### ISSUE TITLE
Extension forgiveness

### ISSUE THREAD

**Issue by hallaathrad** [jharris4/html-webpack-include-assets-plugin#6]
Noticed a JS file served without the extension will not be recognised as a valid asset to include (as stated well in the instructions, resulting in an error).
What would be a quick and easy way to turn that extension enforcement, and is there any chance we could make that a feature/option?

**Comment by jharris4** [comment]
I'd been meaning to get to this for a while... Just tagged version 0.0.6 with two new options: `jsExtensions` and `cssExtensions`.

Check out the update README for details / examples.

**Comment by mmiller42** [comment]
This is a nice enhancement, but it'd be even cooler if you could set this on an individual asset level, manually. For example, the URL `https://fonts.googleapis.com/css?family=Material+Icons` loads a CSS document but doesn't have any extension at all. It'd be neat if, when specifying assets, you could simply override its detection, e.g.

```js
assets: [
  'some/file.js',
  { path: 'https://fonts.googleapis.com/css?family=Material+Icons', type: 'css' },
  'some/file.css',
]
```

Would you be open to that kind of configuration? If so, I'd be happy to contribute and open up a PR for this kind of thing.

**Comment by jharris4** [comment]
Absolutely! And I see you've already created one, I'll take a look
