### ISSUE TITLE
multiple entries support

### ISSUE THREAD

**Issue by damianobarbati** [jharris4/html-webpack-include-assets-plugin#7]
Can you add support for the `[name]` placeholder? So we can use the plugin dynamically and accordingly to entries.

**Comment by jharris4** [comment]
Could you please be more specific? An example of what you are trying to do (or better yet a PR) would help.

**Comment by damianobarbati** [comment]
Sure, give me a couple of hours, I think the `files` options resolve the scenario and I'm trying it out. Thanks! :)

**Comment by damianobarbati** [comment]
@jharris4 I solved with the files option, thanks!
